### ISSUE TITLE
Please push current version to npm

### ISSUE THREAD

**Issue by m-lautenbach** [component/emitter#76]
Hello @vendethiel @julienfouilhe @jonathanong ,

Could you push the current version to npm?
That would help us immensely.

Best Regards

**Comment by vendethiel** [comment]
I can't.

**Comment by jonathanong** [comment]
@vendethiel what's your npm user name?

**Comment by vendethiel** [comment]
actually had it on my old npm handle. should be done.

**Comment by m-lautenbach** [comment]
Sorry, but the npm version still seems to be outdated.
