### ISSUE TITLE
npm ERR! 403 Forbidden - archive/1.0.1.tar.gz 

### ISSUE THREAD

**Issue by eddyparkinson** [component/emitter#83]
From: https://github.com/audreyt/ethercalc/issues/548

Any ideas what is causing this error:

npm ERR! 403 Forbidden: emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz

I see there is no folder /archive/

My emitter/package.json
---
```

{
  "_args": [
    [
      {
        "raw": "emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz",
        "scope": null,
        "escapedName": "emitter",
        "name": "emitter",
        "rawSpec": "http://github.com/component/emitter/archive/1.0.1.tar.gz",
        "spec": "http://github.com/component/emitter/archive/1.0.1.tar.gz",
        "type": "remote"
      },

...
```

**Comment by annawang1** [comment]
i met the same issue, have you solve the issue?

**Comment by eddyparkinson** [comment]
My best guess is emitter was updated and the archive/1.0.1.tar.gz file was removed because it is not needed. Suggest searching for an npm version of emitter that works.

**Comment by gseroul** [comment]
Hi I also have this issue trying to install ethercalc. How can we do to use the latest version of emitter during a npm install of ethercalc ?  I don't know which package is emitter dependent.

**Comment by vendethiel** [comment]
I don't think that's an issue an our part.

**Comment by reverseAndroid** [comment]
How to solve this problem? Ask for help @vendethiel @eddyparkinson

**Comment by vendethiel** [comment]
Github rate limiting in effect

**Comment by eddyparkinson** [comment]
@reverseAndroid for ethercalc, this looks like a warning, rather than an error. Although it might cause an install error if you are using a proxy.

The solution would be to use a different version of emitter. i.e. change the version number in package.json
