### ISSUE TITLE
[Feature proposal] promise support

### ISSUE THREAD

**Issue by y-nk** [component/emitter#88]
I'd like to know if you'd were open to add a simple "async/await" support in `.emit` to be able to respect order of execution within the emit loop:

```diff
- Emitter.prototype.emit = function(event){
+ Emitter.prototype.emit = async function(event){
  this._callbacks = this._callbacks || {};

  var args = new Array(arguments.length - 1)
    , callbacks = this._callbacks['$' + event];

  for (var i = 1; i < arguments.length; i++) {
    args[i - 1] = arguments[i];
  }

  if (callbacks) {
    callbacks = callbacks.slice(0);
    for (var i = 0, len = callbacks.length; i < len; ++i) {
-      callbacks[i].apply(this, args);
+      await callbacks[i].apply(this, args);
    }
  }

  return this;
};
```

It should not break anything for normal synchronous code, but would add that promises are respected if you were to have a usecase (such as mine):

```
on("someEvent", async () => {
  const data = await needToCallBackend()
  someExternalCallback(data)
})

on("someEvent", () => {
 // later listener added which should execute after, but will execute before since the 1st one has "async"
})
```

I hope this is clear enough and that it makes sense for you too.
If you have some guidance over how to solve my usecase without this proposal, i'm in for it too.

Thanks

**Comment by codenomnom** [comment]
What that means is that it will block the loop, and any new coming events will get delayed. All of that is against the nature of how JS works 😃

**Comment by y-nk** [comment]
@codenomnom This would _not_ block the loop in normal cases where the code is synchronous which is 99% of the cases i guess ; coming events would be delayed by less-than-a-tick and the order of event would still be guaranteed nonetheless. If anything it would ensure that the execution of the code could, optionally, retain some soft of order when dealing with asynchronous related tasks.

Don't worry much bc my issue was reported about 2 years ago and i moved on since :) FYI some people make it work despite the worry about "the nature of how JS works" 🤷‍♂️ https://github.com/sindresorhus/emittery
